name: make_flutter_launch_json
description: A sample command-line application.
version: 1.0.0
repository: https://github.com/enoosoft/make_flutter_launch_json.git

environment:
  sdk: ^3.2.0-210.2.beta

# Add regular dependencies here.
dependencies:  
  json_pretty: ^1.0.4
  process_run: ^0.13.1

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
